services:
  vault:
    image: hashicorp/vault:latest
    container_name: mailguard-vault
    ports:
      - "8200:8200"
    user: "0:0"
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/data"}}, "listener": [{"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}}], "ui": true, "disable_mlock": true, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    command: vault server -config=/vault/config/local.json
    volumes:
      - vault-data:/vault/data
    cap_add:
      - IPC_LOCK
    networks:
      - mailguard-net
  gateway:
    build: ./services/gateway
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - vault
      - phishing-detector
    networks:
      - mailguard-net

  ai-service:
    build: ./services/ai-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vault
    networks:
      - mailguard-net

  phishing-detector:
    build: ./services/phishing-detector
    ports:
      - "1025:1025"
      - "8001:8001"
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    depends_on:
      - vault
    networks:
      - mailguard-net

networks:
  mailguard-net:
    driver: bridge
volumes:
  vault-data:
